"""MAF-P0: first end-to-end periodic audio codec prototype."""

from .additive_oracle import AdditiveOracleResult, run_additive_atom_oracle
from .analytic_oracle import (
    AnalyticOracleResult,
    run_analytic_oscillator_oracle,
)
from .anonymous_spectral_factor import (
    AnonymousSpectralFactorization,
    AnonymousSpectralLanguage,
    infer_anonymous_spectral_factors,
)
from .anonymous_causal_program import (
    AnonymousCausalProgramCandidate,
    AnonymousCausalProgramLanguage,
    AnonymousProgramColumn,
    compile_anonymous_causal_program,
    decode_anonymous_causal_program,
)
from .morphing_partial_field import (
    MorphingPartialLanguage,
    MorphingPartialPrediction,
    fit_morphing_partial_prediction,
)
from .convolutive_anonymous_field import (
    ConvolutiveAnonymousField,
    ConvolutiveAnonymousLanguage,
    factor_convolutive_magnitude,
    infer_convolutive_anonymous_fields,
    reconstruct_convolutive_magnitude,
)
from .convolutive_factorized_latent_field import (
    ConvolutiveFactorizedLatentField,
    infer_convolutive_factorized_latent_field,
)
from .coherent_partial_bundle import (
    CausalLaneField,
    CausalLaneObservation,
    CoherentPartialBasis,
    CoherentPartialLanguage,
    PartialBundleObservation,
    infer_causal_lane_field,
)
from .causal_sequence_atlas import (
    CanonicalCausalStream,
    CausalAtlasLanguage,
    CausalEvent,
    MultiLaneCausalSequenceAtlas,
    CausalSequenceAtlas,
    CausalSequenceCandidate,
    build_causal_sequence_atlas,
    build_multilane_causal_sequence_atlas,
    causal_events_from_lane_observations,
    causal_events_from_partial_bases,
    canonicalize_causal_events,
    factorized_causal_event_laws,
    project_causal_events,
)
from .causal_law_grammar import (
    CausalLawGrammarCandidate,
    CausalLawGrammarLanguage,
    CausalLawRule,
    decode_causal_law_tokens,
    encode_causal_law_tokens,
)
from .causal_event_ledger import (
    CausalEventLedgerCandidate,
    decode_causal_event_ledger,
    encode_causal_event_ledger,
)
from .causal_basis_field import (
    CausalBasisFieldCandidate,
    CausalBasisFieldInfo,
    encode_causal_basis_field_from_mft1,
    parse_causal_basis_field,
)
from .causal_basis_truth_candidate import (
    CausalBasisTruthCandidate,
    decode_causal_basis_truth_candidate,
    encode_causal_basis_truth_candidate,
)
from .cached_additive_oracle import (
    CachedAdditiveOracleResult,
    pack_registry_model,
    run_cached_additive_oracle,
)
from .codec import DecodeResult, EncodeResult, decode_bytes, encode_samples
from .foundry_cuda import (
    FoundryCudaError,
    FoundryCudaEvidence,
    GainPhaseCudaFoundry,
)
from .factorized_latent_field import (
    FactorizedLatentField,
    infer_factorized_latent_field,
)
from .complete_pattern_field import (
    CompletePatternResult,
    PatternFieldCandidate,
    PatternLanguage,
    PatternLocation,
    PatternMatch,
    PatternRdoCandidate,
    PatternRdoResult,
    PatternScale,
    ScaleEvidence,
    assert_cpu_gpu_parity,
    encode_complete_pattern_field_candidate,
    search_complete_pattern_field,
    select_complete_pattern_cover,
)
from .hierarchical_grammar import (
    CompoundDiscovery,
    GrammarSelection,
    GrammarSpan,
    StateAtom,
    discover_affine_state_compounds,
    discover_exact_compounds,
    discover_interval_compounds,
    select_minimum_description,
)
from .gridless_truth_rdo import (
    GridlessTruthCandidate,
    GridlessWarpMatch,
    GridlessWarpSearch,
    encode_gridless_truth_candidate,
    search_gridless_warp_field,
)
from .latent_source_field import (
    LatentComponent,
    LatentOccurrence,
    LatentSourceField,
    LatentSourceLanguage,
    infer_latent_source_pattern_field,
)
from .model import (
    encode_basis_latent,
    load_analysis_model,
    save_analysis_model,
    train_linear_cibs,
)
from .lpc_oracle import (
    LPCBlockInfo,
    LPCOracleResult,
    decode_lpc_liftpack_block,
    decode_lpc_liftpack_oracle,
    encode_lpc_liftpack_oracle,
    index_lpc_liftpack_blocks,
    run_lpc_liftpack_oracle,
)
from .lspf_analysis_policy import (
    LspfAnalysisPlan,
    LspfPolicyRequest,
    choose_lspf_analysis_plan,
)
from .lspf_duration_rdo import (
    LspfDurationCandidate,
    LspfDurationSelection,
    select_lspf_duration_candidate,
)
from .lapped_oracle import (
    LappedAnalysis,
    LappedDecodeResult,
    LappedEncodeResult,
    analyze_lapped_source,
    decode_lapped_stream,
    encode_lapped_analysis,
    encode_lapped_stream,
    pack_lapped_selected_grid,
    pack_lapped_selected_payload,
    synthesize_lapped_selected_grid,
)
from .lapped_streaming import (
    LappedPacketDecodeResult,
    LappedPacketEncodeResult,
    LappedPacketStreamInfo,
    LappedPacketView,
    decode_lapped_chained_packet_view,
    decode_lapped_packet_stream,
    decode_lapped_packet_view,
    encode_lapped_packet_stream,
    encode_lapped_chained_packet_stream,
    encode_lapped_compact_packet_stream,
    encode_lapped_transform_packet_stream,
    index_lapped_packet_stream,
)
from .main0 import (
    Main0DecodeResult,
    Main0EncodeResult,
    Main0State,
    decode_main0_raw_stream,
    encode_main0_periodic_rdo,
    encode_main0_state_rdo,
    pack_main0_cibs_stream,
    pack_main0_raw_stream,
    pack_main0_lpc_residual_stream,
    pack_main0_residual_stream,
    pack_main0_state_stream,
)
from .multichannel import (
    IndependentChannelDecodeResult,
    IndependentChannelEncodeResult,
    decode_main0_independent_stream,
    encode_main0_independent_rdo,
    pack_main0_independent_stream,
)
from .motif_orbit import (
    MotifOrbitCandidate,
    encode_gain_orbit_candidate,
    encode_multichannel_gain_orbit_candidate,
    encode_optimized_independent_truth,
)
from .partial_spectrum_latent_field import (
    PartialSpectrumBandField,
    PartialSpectrumLatentField,
    infer_partial_spectrum_latent_field,
)
from .partial_basis_trajectory import (
    PartialBasisTrajectoryPrediction,
    fit_partial_basis_trajectory_prediction,
)
from .native_core import (
    NativeMain0Decoder,
    NativeMultichannelDecodeResult,
    NativeMultichannelRequirements,
)
from .packet_loss import (
    PacketLossSimulationResult,
    simulate_aligned_packet_loss,
    simulate_lapped_packet_loss,
)
from .opus_anchor import run_opus_multichannel_anchor
from .opus_max_effort import (
    OpusEffortConfig,
    OpusEffortPoint,
    OpusMaxEffortFrontier,
    opus_max_effort_configurations,
    run_opus_max_effort_frontier,
)
from .periodic import PhaseTrajectory
from .residual import ResidualPacket, decode_liftpack, encode_liftpack
from .segmentation import SegmentationResult, segment_acoustic_states
from .sparse_motif_grammar import (
    ComponentTokenObservation,
    LatentFieldEventLedger,
    SparseMotifCandidate,
    SparseMotifDefinition,
    SparseMotifLanguage,
    SparsePathCandidate,
    SparsePathDefinition,
    SparsePathLanguage,
    decode_sparse_motif_events,
    discover_and_pack_sparse_pair_motifs,
    discover_and_pack_sparse_path_motifs,
    pack_latent_field_event_ledger,
    pack_flat_observations,
    pack_basis_grouped_observations,
)
from .stateful import (
    decode_stateful_bytes,
    encode_stateful_rdo_samples,
    encode_stateful_samples,
)
from .wav_io import (
    read_pcm16_channels,
    read_pcm16_mono,
    write_pcm16_channels,
    write_pcm16_mono,
)

__all__ = [
    "AnonymousCausalProgramCandidate",
    "AnonymousCausalProgramLanguage",
    "AnonymousProgramColumn",
    "MorphingPartialLanguage",
    "MorphingPartialPrediction",
    "AdditiveOracleResult",
    "AnalyticOracleResult",
    "AnonymousSpectralFactorization",
    "AnonymousSpectralLanguage",
    "ConvolutiveAnonymousField",
    "ConvolutiveAnonymousLanguage",
    "ConvolutiveFactorizedLatentField",
    "CausalLaneField",
    "CausalLaneObservation",
    "CanonicalCausalStream",
    "CausalAtlasLanguage",
    "CausalEvent",
    "CausalLawGrammarCandidate",
    "CausalLawGrammarLanguage",
    "CausalLawRule",
    "CausalEventLedgerCandidate",
    "CausalBasisFieldCandidate",
    "CausalBasisFieldInfo",
    "CausalBasisTruthCandidate",
    "MultiLaneCausalSequenceAtlas",
    "CausalSequenceAtlas",
    "CausalSequenceCandidate",
    "CoherentPartialBasis",
    "CoherentPartialLanguage",
    "CachedAdditiveOracleResult",
    "DecodeResult",
    "EncodeResult",
    "FoundryCudaError",
    "FoundryCudaEvidence",
    "FactorizedLatentField",
    "GainPhaseCudaFoundry",
    "GridlessTruthCandidate",
    "LatentComponent",
    "LatentOccurrence",
    "LatentSourceField",
    "LatentSourceLanguage",
    "GridlessWarpMatch",
    "GridlessWarpSearch",
    "CompoundDiscovery",
    "GrammarSelection",
    "GrammarSpan",
    "StateAtom",
    "discover_affine_state_compounds",
    "discover_exact_compounds",
    "discover_interval_compounds",
    "select_minimum_description",
    "Main0DecodeResult",
    "Main0EncodeResult",
    "Main0State",
    "IndependentChannelDecodeResult",
    "IndependentChannelEncodeResult",
    "LPCOracleResult",
    "LPCBlockInfo",
    "LspfAnalysisPlan",
    "LspfPolicyRequest",
    "LspfDurationCandidate",
    "LspfDurationSelection",
    "LappedDecodeResult",
    "LappedEncodeResult",
    "LappedAnalysis",
    "LappedPacketDecodeResult",
    "LappedPacketEncodeResult",
    "LappedPacketStreamInfo",
    "LappedPacketView",
    "NativeMain0Decoder",
    "NativeMultichannelDecodeResult",
    "NativeMultichannelRequirements",
    "MotifOrbitCandidate",
    "PartialSpectrumBandField",
    "PartialSpectrumLatentField",
    "PartialBundleObservation",
    "PartialBasisTrajectoryPrediction",
    "PacketLossSimulationResult",
    "OpusEffortConfig",
    "OpusEffortPoint",
    "OpusMaxEffortFrontier",
    "analyze_lapped_source",
    "decode_bytes",
    "decode_main0_raw_stream",
    "decode_main0_independent_stream",
    "encode_main0_periodic_rdo",
    "encode_main0_state_rdo",
    "encode_main0_independent_rdo",
    "encode_gain_orbit_candidate",
    "encode_multichannel_gain_orbit_candidate",
    "encode_optimized_independent_truth",
    "encode_samples",
    "encode_gridless_truth_candidate",
    "infer_latent_source_pattern_field",
    "infer_factorized_latent_field",
    "infer_anonymous_spectral_factors",
    "fit_morphing_partial_prediction",
    "compile_anonymous_causal_program",
    "decode_anonymous_causal_program",
    "factor_convolutive_magnitude",
    "infer_convolutive_anonymous_fields",
    "infer_convolutive_factorized_latent_field",
    "infer_causal_lane_field",
    "reconstruct_convolutive_magnitude",
    "infer_partial_spectrum_latent_field",
    "fit_partial_basis_trajectory_prediction",
    "choose_lspf_analysis_plan",
    "build_causal_sequence_atlas",
    "build_multilane_causal_sequence_atlas",
    "causal_events_from_lane_observations",
    "decode_causal_law_tokens",
    "decode_causal_event_ledger",
    "decode_causal_basis_truth_candidate",
    "encode_causal_law_tokens",
    "encode_causal_event_ledger",
    "encode_causal_basis_field_from_mft1",
    "encode_causal_basis_truth_candidate",
    "factorized_causal_event_laws",
    "project_causal_events",
    "parse_causal_basis_field",
    "causal_events_from_partial_bases",
    "canonicalize_causal_events",
    "select_lspf_duration_candidate",
    "pack_main0_cibs_stream",
    "pack_main0_raw_stream",
    "pack_main0_lpc_residual_stream",
    "pack_main0_residual_stream",
    "pack_main0_state_stream",
    "pack_main0_independent_stream",
    "pack_registry_model",
    "decode_stateful_bytes",
    "encode_stateful_samples",
    "encode_stateful_rdo_samples",
    "PhaseTrajectory",
    "ResidualPacket",
    "decode_liftpack",
    "decode_lpc_liftpack_oracle",
    "decode_lpc_liftpack_block",
    "decode_lapped_stream",
    "decode_lapped_packet_stream",
    "decode_lapped_chained_packet_view",
    "decode_lapped_packet_view",
    "encode_lapped_analysis",
    "encode_liftpack",
    "encode_lpc_liftpack_oracle",
    "encode_lapped_stream",
    "encode_lapped_packet_stream",
    "encode_lapped_chained_packet_stream",
    "encode_lapped_compact_packet_stream",
    "encode_lapped_transform_packet_stream",
    "index_lapped_packet_stream",
    "pack_lapped_selected_grid",
    "pack_lapped_selected_payload",
    "synthesize_lapped_selected_grid",
    "index_lpc_liftpack_blocks",
    "SegmentationResult",
    "ComponentTokenObservation",
    "LatentFieldEventLedger",
    "SparseMotifCandidate",
    "SparseMotifDefinition",
    "SparseMotifLanguage",
    "SparsePathCandidate",
    "SparsePathDefinition",
    "SparsePathLanguage",
    "decode_sparse_motif_events",
    "discover_and_pack_sparse_pair_motifs",
    "discover_and_pack_sparse_path_motifs",
    "pack_latent_field_event_ledger",
    "pack_flat_observations",
    "pack_basis_grouped_observations",
    "segment_acoustic_states",
    "simulate_aligned_packet_loss",
    "simulate_lapped_packet_loss",
    "encode_basis_latent",
    "load_analysis_model",
    "save_analysis_model",
    "train_linear_cibs",
    "read_pcm16_mono",
    "read_pcm16_channels",
    "run_additive_atom_oracle",
    "run_analytic_oscillator_oracle",
    "run_cached_additive_oracle",
    "run_lpc_liftpack_oracle",
    "run_opus_multichannel_anchor",
    "opus_max_effort_configurations",
    "run_opus_max_effort_frontier",
    "search_gridless_warp_field",
    "write_pcm16_mono",
    "write_pcm16_channels",
]
