"""Generate the reviewed quarter-wave ROM used by the native lapped kernel."""

from __future__ import annotations

import argparse
import hashlib
import math
from pathlib import Path
import struct


MAXIMUM_HALF_WINDOW = 1024
QUARTER_SAMPLES = 2 * MAXIMUM_HALF_WINDOW + 1


def _table(fraction_bits: int) -> list[int]:
    scale = 1 << fraction_bits
    return [
        round(
            math.cos(index * math.pi / (4 * MAXIMUM_HALF_WINDOW))
            * scale
        )
        for index in range(QUARTER_SAMPLES)
    ]


def _format_array(name: str, values: list[int]) -> str:
    rows = []
    for start in range(0, len(values), 12):
        row = ", ".join(str(value) for value in values[start : start + 12])
        rows.append(f"    {row},")
    return (
        f"constexpr std::array<std::int32_t, {len(values)}> {name} = {{\n"
        + "\n".join(rows)
        + "\n};\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "output",
        type=Path,
        nargs="?",
        default=(
            Path(__file__).resolve().parents[1]
            / "native"
            / "src"
            / "lapped_rom.inc"
        ),
    )
    args = parser.parse_args()
    q14 = _table(14)
    q15 = _table(15)
    canonical = b"".join(
        struct.pack("<i", value)
        for table in (q14, q15)
        for value in table
    )
    digest = hashlib.sha256(canonical).hexdigest()
    content = (
        "/* Generated by scripts/generate_lapped_rom.py; do not hand-edit. */\n"
        f"/* Canonical little-endian int32 SHA-256: {digest} */\n"
        + _format_array("kCosineQuarterQ14", q14)
        + "\n"
        + _format_array("kCosineQuarterQ15", q15)
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8", newline="\n")
    print(digest)


if __name__ == "__main__":
    main()
