"""Generate the small Python-authored LPF1 native conformance vector."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import numpy as np


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "reference"))

from maf_p0.lapped_oracle import (  # noqa: E402
    analyze_lapped_source,
    encode_lapped_stream,
)
from maf_p0.lapped_streaming import (  # noqa: E402
    encode_lapped_compact_packet_stream,
    encode_lapped_packet_stream,
    encode_lapped_transform_packet_stream,
)


def _array(
    cpp_type: str,
    name: str,
    values: list[int],
    *,
    hexadecimal: bool,
    per_row: int,
) -> str:
    rendered = [
        f"0x{value:02x}" if hexadecimal else str(value)
        for value in values
    ]
    rows = [
        "    " + ", ".join(rendered[start : start + per_row]) + ","
        for start in range(0, len(rendered), per_row)
    ]
    return (
        f"constexpr std::array<{cpp_type}, {len(values)}> {name} = {{\n"
        + "\n".join(rows)
        + "\n};\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "output",
        type=Path,
        nargs="?",
        default=PROJECT_ROOT / "native" / "tests" / "lapped_vector.inc",
    )
    args = parser.parse_args()
    frame = np.arange(96, dtype=np.float64)
    samples = np.stack(
        (
            np.rint(
                12000 * np.sin(2 * np.pi * frame / 29)
                + 3000 * np.sin(2 * np.pi * frame / 11)
            ),
            np.rint(
                9000 * np.sin(2 * np.pi * frame / 37 + 0.3)
            ),
        ),
        axis=1,
    ).astype(np.int16)
    encoded = encode_lapped_stream(
        samples,
        48000,
        coefficients_per_frame=8,
        half_window=32,
        band_count=4,
        entropy_backend="bounded",
        transform_backend="fixed",
    )
    adaptive = encode_lapped_stream(
        samples,
        48000,
        coefficients_per_frame=8,
        half_window=32,
        band_count=4,
        entropy_backend="bounded",
        transform_backend="fixed",
        density_backend="adaptive",
    )
    analysis = analyze_lapped_source(
        samples,
        48000,
        half_window=32,
        band_count=4,
        transform_backend="fixed",
    )
    packeted = encode_lapped_packet_stream(
        samples,
        48000,
        coefficients_per_frame=8,
        packet_frames=64,
        half_window=32,
        band_count=4,
        density_backend="fixed",
    )
    transform_packeted = encode_lapped_transform_packet_stream(
        samples,
        48000,
        coefficients_per_frame=8,
        packet_frames=64,
        half_window=32,
        band_count=4,
    )
    compact_packeted = encode_lapped_compact_packet_stream(
        samples,
        48000,
        coefficients_per_frame=8,
        packet_frames=64,
        half_window=32,
        band_count=4,
    )
    content = (
        "/* Generated by scripts/generate_lapped_vector.py. */\n"
        + _array(
            "std::int16_t",
            "kLappedSourcePcm",
            samples.reshape(-1).astype(int).tolist(),
            hexadecimal=False,
            per_row=12,
        )
        + "\n"
        + _array(
            "std::uint8_t",
            "kExpectedLappedScales",
            analysis.scales.reshape(-1).astype(int).tolist(),
            hexadecimal=False,
            per_row=12,
        )
        + "\n"
        + _array(
            "std::int16_t",
            "kExpectedLappedQuantized",
            analysis.quantized_grid.reshape(-1).astype(int).tolist(),
            hexadecimal=False,
            per_row=12,
        )
        + "\n"
        + _array(
            "std::uint64_t",
            "kExpectedLappedScores",
            analysis.score_grid.reshape(-1).astype(np.uint64).tolist(),
            hexadecimal=False,
            per_row=8,
        )
        + "\n"
        + _array(
            "std::uint8_t",
            "kLappedStream",
            list(encoded.payload),
            hexadecimal=True,
            per_row=12,
        )
        + "\n"
        + _array(
            "std::uint8_t",
            "kLappedPacketStream",
            list(packeted.payload),
            hexadecimal=True,
            per_row=12,
        )
        + "\n"
        + _array(
            "std::uint8_t",
            "kLappedTransformPacketStream",
            list(transform_packeted.payload),
            hexadecimal=True,
            per_row=12,
        )
        + "\n"
        + _array(
            "std::uint8_t",
            "kLappedCompactPacketStream",
            list(compact_packeted.payload),
            hexadecimal=True,
            per_row=12,
        )
        + "\n"
        + _array(
            "std::int16_t",
            "kExpectedLappedPcm",
            encoded.reconstruction.reshape(-1).astype(int).tolist(),
            hexadecimal=False,
            per_row=12,
        )
        + "\n"
        + _array(
            "std::uint8_t",
            "kAdaptiveLappedStream",
            list(adaptive.payload),
            hexadecimal=True,
            per_row=12,
        )
        + "\n"
        + _array(
            "std::int16_t",
            "kExpectedAdaptiveLappedPcm",
            adaptive.reconstruction.reshape(-1).astype(int).tolist(),
            hexadecimal=False,
            per_row=12,
        )
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8", newline="\n")
    print(encoded.report["stream_sha256"])


if __name__ == "__main__":
    main()
